spring:
  datasource:
    username: root
    password: taxisharing1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.209.32.171:3306/taxi_db

  profiles:
    include: aws

jwt:
  secreteKey: ABCDEFG
  expire-length: 600000

logging:
  config: classpath:logback-spring.xml

iamport:
  key: 6728211803389795
  secret: 1fa326bb49b98823c8847237f50da27877ac316609b910d9193fcfa5fd6700c7c06060dfb528b285